dist: trusty
language: c

compiler:
  - gcc

cache:
  - ccache
  - pip

before_install:
  - sudo add-apt-repository --yes ppa:vala-team
  - sudo apt-get update --quiet
  - sudo apt-get install --yes --force-yes
    valac valadoc gtk-doc-tools python3-pip gcovr
    libglib2.0-bin libglib2.0-dev libgee-0.8-dev
  - pip3 install --user meson
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip -d ${HOME}/.local/bin

before_script:
  - mkdir build
  - meson -D b_coverage=true -D build_valadoc=valadoc,gtkdoc build
  - ninja -C build -v

script:
  - meson test -C build --repeat 2 -t 20 --print-errorlogs --verbose
  - DESTDIR=$(mktemp -d) ninja -C build -v install

after_success:
  - bash <(curl -s https://codecov.io/bash)
